modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="justify_portal_gun"
version="${version}"
displayName="Justify Portal Gun"
logoFile="assets/justify_portal_gun/icon.png"
description="Portal guns, seamless portals and Companion Cubes. Requires matching Justify API."
displayURL="https://github.com/MrAskick/justifyportalgun"
[[dependencies.justify_portal_gun]]
modId="justify_api"
mandatory=true
versionRange="[${version}]"
ordering="AFTER"
side="BOTH"
[[dependencies.justify_portal_gun]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
